#! /usr/bin/python3

# Convert a font C source file to Python source.

# Copyright Peter Hinch 2016
# Released under the MIT licence
# Files created by GLCD Font Creator http://www.mikroe.com/glcd-font-creator/
# The code attempts two ways of deducing font height and width in pixels.
# Files produced by the GLCD Font Creator have a '//GLCD FontSize'  comment line which species these.
# This is used if it exists. However some files on the website lack this and have an initial record
# written into the data: this is used if necessary.

# Usage:
# ./cfonts_to_python Arial16x16.c timesroman.c
# puts files into a single Python file defaulting to fonts.py (-o name can override default)
# with a dictionary enabling a PyFont object to be retrieved by name (the name being the font filename less path and extension)

import argparse, os

def getname(sourcefile):
    return os.path.basename(os.path.splitext(sourcefile)[0])

def writestart(outfile, name):
    print('{}: header found'.format(name))
    outfile.write('_')
    outfile.write(name) # _fontname = b'
    outfile.write(" = b'")

def process(infile, outfile, sourcefile):
    chars_processed = 0
    horiz, vert = 0, 0
    name = getname(sourcefile)
    phase = 0
    header_done = False
    for line in infile:
        if phase == 0:
            start = line.find('//GLCD FontSize')
            if start >= 0:                          # Found the font size: parse line
                start = line.find(':')
                line = line[start +1:]
                operator = line.find('x')
                if operator > 0 :
                    horiz = int(line[ : operator])
                    vert = int(line[operator +1 :])
                    writestart(outfile, name)
                    header_done = True
                    phase = 1
            elif line.find('{') >= 0:
                phase = 1
        if phase == 1:                           # Skip to 1st data after '{'
            start = line.find('{')
            if start >= 0:
                line = line[start +1:]
                phase = 2
        if phase == 2:
            if not (line == '' or line.isspace()):
                comment = line.find('//')
                if comment > 0 :
                    line = line[:comment]
                hexnums = line.split(',')
                if header_done:              # Ignore manually entered header data
                    if len(hexnums) > 5:
                        phase = 3               # Real font data will have many more fields per line
                else:
                    if len(hexnums) <= 5:
                        nums = [x for x in hexnums if not x.isspace()]
                        h = nums[1]
                        v = nums[2]
                        horiz, vert = int(h, 16), int(v, 16)
                        writestart(outfile, name)
                        header_done = True
                    else:
                        break                   # No header data
        if phase == 3:                          # Process data until '}'
            end = line.find('}')
            if end > 0 :
                line = line[:end]
                phase = 4
            comment = line.find('//')
            if comment > 0 :
                line = line[:comment]
            hexnums = line.split(',')
            if hexnums[0] != '':
                for hexnum in [x for x in hexnums if not x.isspace()]:
                    outfile.write('\\')
                    outfile.write(hexnum.strip()[1:5])
                chars_processed += 1
            outfile.write("\\\n")
    if phase == 4 :
        outfile.write("'\n")
        outfile.write(name)
        outfile.write(' = pyfont.PyFont(_') # font array name starts with _
        outfile.write(name)
        outfile.write(', {}, {}, {})'.format(vert, horiz, chars_processed))
        outfile.write('\n\n')
        print('{}: Characters in font: {} width: {} height: {}'.format(name, chars_processed, horiz, vert))
    else:
        print(''.join(("File: '", sourcefile, "' is not a valid C font file")))

def write_header(outfile):
    outfile.write('# Code generated by CfontToPython.py\n')
    outfile.write('import pyfont\n')
  
def write_trailer(sourcefiles, outfile):
    outfile.write('fonts = {')
    for sourcefile in sourcefiles:
        name = getname(sourcefile)
        outfile.write('"')
        outfile.write(name)
        outfile.write('"')
        outfile.write(':')
        outfile.write(name)
        outfile.write(',\n')
    outfile.write('}\n\n')

def load_c(sourcefiles, destfile):
    try:
        with open(destfile, 'w') as outfile:
            write_header(outfile)
            for sourcefile in sourcefiles:
                with open(sourcefile, 'r') as f:
                    process(f, outfile, sourcefile)
            write_trailer(sourcefiles, outfile)
    except OSError as err:
        print(err)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(__file__, description="Convert C fonts generated by GLCD font creator to Python.\nSample usage:\n ./CfontToPython Arial16x16.c ubuntu5x7.py\nProduces fonts.py")
    parser.add_argument('infiles', metavar='N', type=str, nargs='+', help='input file paths')
    parser.add_argument("--outfile", "-o", default='fonts.py', help="Path and name of output file", required=False)
    args = parser.parse_args()
    errlist = [f for f in args.infiles if not f[0].isalpha()]
    if len(errlist):
        print('Font filenames must be valid Python variable names:')
        for f in errlist:
            print(f)
    else:
        load_c(args.infiles, args.outfile)

